### ISSUE TITLE
Add information about reference architectures for deployable architectures

### ISSUE THREAD

**Issue by SirSpidey** [terraform-ibm-modules/terraform-ibm-issue-tracker#54]
Add information to the [docs](https://terraform-ibm-modules.github.io/documentation/) and to the module-template to provide structure and guidance for how to include a reference architecture.

Include links to Cloud docs (only in test).

### Tasks
- [x] Add optional Reference architecture section to module-template [readme file](https://github.com/terraform-ibm-modules/terraform-ibm-module-template/blob/main/README.md)
- [x] Add a markdown template to the [Docs](https://github.com/terraform-ibm-modules/documentation/tree/main/docs/templates)
- [x] Docs: Add reference architecture to the [module structure](https://terraform-ibm-modules.github.io/documentation/#/module-structure) page.
- [x] Docs: Add a Reference architecture section to the [Authoring guidelines](https://terraform-ibm-modules.github.io/documentation/#/implementation-guidelines) page.
